export const IS_ONLINE = 'IS_ONLINE'
export const PRE_EMAIL = 'hruday@gmail.com'
export const PRE_PASSWORD = 'hruday123'
export const MSG = 'Login Successfull'
export const ERROR_MSG = 'Please check user name or Password'
export const NOTE = 'Note: App is designed in such a way that "Login Button" works if you have only Internet Connection'